/* Exotic armor, class-item, intrinsic, and exotic weapon data
   Extracted from the original monolithic index.html without behavioral rewrites. */
// ---- EXOTIC ARMOR ----
// Each piece is tagged with `synergy`: the element(s) whose verbs/kits it
// plugs into. "Any" means it works regardless of subclass element (usually
// because it boosts abilities/weapons generically rather than a Light/Dark verb).
const EXOTIC_ARMOR = {
  Titan: [
    // Solar
    {name:"Ashen Wake", piece:"Arms", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"grenadeDamage",value:12,note:"Fusion Grenades detonate on impact, recharge on kills"}]},
    {name:"Hallowfire Heart", piece:"Chest", synergy:["Solar"], grants:[], effects:[{bucket:"grenadeEnergy",value:12,note:"ability recharge, faster with charged super"},{bucket:"classEnergy",value:10}]},
    {name:"Khepri's Horn", piece:"Head", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"classEnergy",value:8,note:"weapon kills recharge Barricade; cast blasts Solar fire"}]},
    {name:"Loreley Splendor Helm", piece:"Head", synergy:["Solar"], grants:["restoration","radiant"], effects:[{bucket:"healing",value:20,cond:"restoration"}]},
    {name:"Phoenix Cradle", piece:"Legs", synergy:["Solar"], grants:["restoration"], effects:[{bucket:"healing",value:10,note:"extends Sunspots, shares buff with allies"}]},
    {name:"The Path of Burning Steps", piece:"Legs", synergy:["Solar"], grants:["radiant"], effects:[{bucket:"damage",value:12,note:"stacking weapon dmg on Solar final blows; freeze resist"}]},
    // Arc
    {name:"An Insurmountable Skullfort", piece:"Head", synergy:["Arc"], grants:[], effects:[{bucket:"healing",value:10,note:"melee kills trigger health regen"},{bucket:"meleeEnergy",value:10,note:"refunds all melee energy"}]},
    {name:"Cuirass of the Falling Star", piece:"Chest", synergy:["Arc"], grants:[], effects:[{bucket:"damage",value:25,note:"Thundercrash-style super crit swap"}]},
    {name:"Eternal Warrior", piece:"Head", synergy:["Arc"], grants:["overshield"], effects:[{bucket:"dr",value:12,cond:"overshield",note:"overshield on Fists of Havoc cast"}]},
    {name:"Point-Contact Cannon Brace", piece:"Arms", synergy:["Arc"], grants:["jolt"], effects:[{bucket:"damage",value:15,cond:"jolt"},{bucket:"meleeEnergy",value:8}]},
    // Void
    {name:"Doom Fang Pauldron", piece:"Arms", synergy:["Void"], grants:[], effects:[{bucket:"superEnergy",value:15,note:"melee final blows vs powerful"},{bucket:"damage",value:6,note:"escalating Void weapon dmg on kills"}]},
    {name:"Helm of Saint-14", piece:"Head", synergy:["Void"], grants:["overshield"], effects:[{bucket:"dr",value:15,note:"Ward of Dawn blinds enemies inside, grants allies overshield"}]},
    {name:"No Backup Plans", piece:"Arms", synergy:["Void"], grants:["overshield"], effects:[{bucket:"dr",value:12,cond:"overshield",note:"Shotgun final blows activate overshield"},{bucket:"healing",value:6}]},
    {name:"Second Chance", piece:"Arms", synergy:["Void"], grants:["weaken"], effects:[{bucket:"meleeDamage",value:10,note:"second Shield Throw charge, pierces Barrier, weakens"}]},
    {name:"Ursa Furiosa", piece:"Arms", synergy:["Void"], grants:["overshield"], effects:[{bucket:"superEnergy",value:10,note:"blocked damage converts to Super energy"},{bucket:"classEnergy",value:6}]},
    // Strand
    {name:"Abeyant Leap", piece:"Legs", synergy:["Strand"], grants:["suspend","woven-mail"], effects:[{bucket:"meleeEnergy",value:12,cond:"suspend",note:"Barricade launches 3 tracking Suspend ripples, grants Woven Mail"}]},
    // Stasis
    {name:"Cadmus Ridge Lancecap", piece:"Head", synergy:["Stasis"], grants:["frozen"], effects:[{bucket:"grenadeEnergy",value:10,cond:"frozen",note:"rally barricade + Stasis weapon creates Diamond Lances"}]},
    {name:"Hoarfrost-Z", piece:"Chest", synergy:["Stasis"], grants:["overshield"], effects:[{bucket:"dr",value:20,cond:"frozen"}]},
    {name:"Icefall Mantle", piece:"Arms", synergy:["Stasis"], grants:["overshield","frozen"], effects:[{bucket:"dr",value:15,cond:"overshield"}]},
    // Kinetic / Neutral
    {name:"ACD/0 Feedback Fence", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeEnergy",value:8,note:"melee hits build charges"},{bucket:"dr",value:6,note:"taking melee dmg releases shockwave"}]},
    {name:"Actium War Rig", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"grenadeEnergy",value:8,note:"auto-reloads Auto Rifles/LMGs from reserves"}]},
    {name:"Antaeus Wards", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:10,note:"sliding reflects projectiles after sprinting"}]},
    {name:"Armamentarium", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"grenadeEnergy",value:8,note:"extra grenade charge, any subclass"}]},
    {name:"Citan's Ramparts", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:10,note:"allies can shoot through your Towering Barricade"}]},
    {name:"Crest of Alpha Lupi", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"superEnergy",value:6,note:"extra orb from supers"},{bucket:"healing",value:6,note:"healing pulse on Barricade"}]},
    {name:"Dunemarchers", piece:"Legs", synergy:["Arc"], grants:["jolt"], effects:[{bucket:"meleeDamage",value:10,cond:"jolt"},{bucket:"classEnergy",value:6,note:"sprint speed"}]},
    {name:"Heart of Inmost Light", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"meleeEnergy",value:10},{bucket:"grenadeEnergy",value:10},{bucket:"classEnergy",value:10}]},
    {name:"Lion Rampant", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:6,note:"airborne maneuverability + hip-fire accuracy"}]},
    {name:"Mask of the Quiet One", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"ability energy when taking damage"},{bucket:"healing",value:8,note:"crit-health kills regen health"}]},
    {name:"Mk. 44 Stand Asides", piece:"Legs", synergy:["Any"], grants:["overshield"], effects:[{bucket:"dr",value:10,cond:"overshield",note:"overshield sprinting at full health w/ shoulder charge"},{bucket:"meleeEnergy",value:6}]},
    {name:"One-Eyed Mask", piece:"Head", synergy:["Any"], grants:["overshield"], effects:[{bucket:"dr",value:10,cond:"overshield",note:"marks attacker, defeating them grants overshield"}]},
    {name:"Peacekeepers", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"SMG handling/reload/movement speed"}]},
    {name:"Peregrine Greaves", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"meleeDamage",value:14,note:"airborne shoulder charge vs minibosses/champs/vehicles"}]},
    {name:"Precious Scars", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:12,cond:"matching-element",note:"matching-element final blows heal you and allies"}]},
    {name:"Severance Enclosure", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"powered melee/finisher kills trigger a kinetic explosion"}]},
    {name:"Stronghold", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:12,note:"sword guard costs zero ammo; parries heal heavily"}]},
    {name:"Synthoceps", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeDamage",value:15,note:"while surrounded"},{bucket:"damage",value:8,note:"super dmg while surrounded"}]},
    {name:"Wormgod Caress", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeDamage",value:16,note:"escalating melee kill stacks"}]},
    // Prismatic-only exotic class item
    {name:"Stoicism", piece:"ClassItem", synergy:["Any"], grants:[], effects:[], note:"Prismatic-only exotic class item — pick 2 perks below (one per column)"},
  ],
  Hunter: [
    // Solar
    {name:"Celestial Nighthawk", piece:"Head", synergy:["Solar"], grants:[], effects:[{bucket:"damage",value:30,note:"single-shot Golden Gun crit swap"}]},
    {name:"Ophidia Spathe", piece:"Chest", synergy:["Solar"], grants:[], effects:[{bucket:"meleeEnergy",value:8,note:"two knives per charge"}]},
    {name:"Shards of Galanor", piece:"Arms", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"superEnergy",value:15,note:"Blade Barrage kill energy return"}]},
    {name:"Young Ahamkara's Spine", piece:"Arms", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"meleeDamage",value:18,cond:"scorch",note:"enhanced Tripmine duration/radius"}]},
    {name:"Caliban's Hand", piece:"Arms", synergy:["Solar"], grants:["scorch","ignite"], effects:[{bucket:"meleeDamage",value:12,note:"proximity knives cause ignitions on final blows"}]},
    // Arc
    {name:"Blight Ranger", piece:"Head", synergy:["Arc"], grants:["jolt"], effects:[{bucket:"damage",value:10,note:"redirected Arc Staff projectile damage"}]},
    {name:"Liar's Handshake", piece:"Arms", synergy:["Arc"], grants:[], effects:[{bucket:"meleeDamage",value:16},{bucket:"healing",value:10,note:"melee counter-punch heal"}]},
    {name:"Lucky Raspberry", piece:"Chest", synergy:["Arc"], grants:["jolt"], effects:[{bucket:"grenadeEnergy",value:10,note:"Arcbolt grenade chaining/recharge"}]},
    {name:"Raiju's Harness", piece:"Chest", synergy:["Arc"], grants:["amplified"], effects:[{bucket:"superEnergy",value:8,note:"deactivate Arc Staff early to save energy"}]},
    {name:"Raiden Flux", piece:"Chest", synergy:["Arc"], grants:[], effects:[{bucket:"damage",value:10,note:"Arc Staff duration/damage with consecutive hits"}]},
    {name:"Shinobu's Vow", piece:"Arms", synergy:["Arc"], grants:[], effects:[{bucket:"grenadeEnergy",value:10,note:"Skip grenades extra charge"}]},
    // Void
    {name:"Graviton Forfeit", piece:"Head", synergy:["Void"], grants:["invisible"], effects:[{bucket:"dr",value:8,cond:"invisible"},{bucket:"meleeEnergy",value:8}]},
    {name:"Gwisin Vest", piece:"Chest", synergy:["Void"], grants:[], effects:[{bucket:"superEnergy",value:12,note:"Spectral Blades kills return Super energy"}]},
    {name:"Khepri's Sting", piece:"Arms", synergy:["Void"], grants:["invisible"], effects:[{bucket:"damage",value:10,note:"smoke bombs grant Truesight and deal damage"}]},
    {name:"Omnioculus", piece:"Chest", synergy:["Void"], grants:["invisible","overshield"], effects:[{bucket:"dr",value:10,cond:"invisible"}]},
    {name:"Gyrfalcon's Hauberk", piece:"Chest", synergy:["Void"], grants:["invisible","volatile"], effects:[{bucket:"damage",value:10,cond:"volatile",note:"volatile rounds after emerging from invis"}]},
    // Strand
    {name:"Cyrtarachne's Facade", piece:"Head", synergy:["Strand"], grants:["woven-mail"], effects:[{bucket:"dr",value:12,cond:"woven-mail",note:"Woven Mail on Grapple activation"}]},
    {name:"Renewal Grasps", piece:"Arms", synergy:["Strand"], grants:["frozen"], effects:[{bucket:"grenadeDamage",value:15,cond:"frozen",note:"Duskfield becomes a large weakening bubble"}]},
    // Stasis
    {name:"Mask of Bakris", piece:"Head", synergy:["Stasis"], grants:["frozen"], effects:[{bucket:"meleeDamage",value:12,note:"teleport dodge buffs Arc/Stasis weapon dmg"}]},
    // Neutral
    {name:"Aeon Swift", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"team-based ammo/ability energy utility"}]},
    {name:"Assassin's Cowl", piece:"Head", synergy:["Any"], grants:["invisible"], effects:[{bucket:"healing",value:12,cond:"invisible"}]},
    {name:"Athrys's Embrace", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeEnergy",value:12,note:"extra knife bounce + tracking"}]},
    {name:"Balance of Power", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"enhances Threaded Decoys"}]},
    {name:"The Bombardiers", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"grenadeDamage",value:10,note:"dodge drops a subclass-specific explosive"}]},
    {name:"Crest of Alpha Lupi", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:8,note:"heals on class ability use"}]},
    {name:"The Dragon's Shadow", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"reload + speed/handling after dodge"}]},
    {name:"Foetracer", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"vs low-health/high-value targets"}]},
    {name:"Fr0st-EE5", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"ability regen while sprinting"}]},
    {name:"Gemini Jester", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:8,note:"disorients enemies, hides radar"}]},
    {name:"Gifted Conviction", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:8,note:"AoE dmg based on movement/ability usage"}]},
    {name:"Knucklehead Radar", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"radar while aiming, marks low-health targets"}]},
    {name:"Lucky Pants", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"Hand Cannon handling/accuracy, stacking dmg"}]},
    {name:"Mechaneer's Tricksleeves", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"Sidearm damage buff when critically wounded"}]},
    {name:"Oathkeeper", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"indefinite Bow draw hold"}]},
    {name:"Radiant Dance Machines", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:8,note:"multiple dodges near enemies"}]},
    {name:"Sealed Ahamkara Grasps", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"melee damage reloads current weapon"}]},
    {name:"The Sixth Coyote", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:10,note:"second dodge charge"}]},
    {name:"Speedloader Slacks", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:8,note:"reload/handling buffs from kills"}]},
    {name:"St0mp-EE5", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"jump height/sprint/slide distance"}]},
    {name:"Star-Eater Scales", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:20,note:"orb pickups overcharge your super"}]},
    {name:"Triton Vice", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeDamage",value:12,note:"Glaive melee/projectile damage"}]},
    {name:"Wormhusk Crown", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:12,note:"heal on dodge"}]},
    // Prismatic-only exotic class item
    {name:"Essentialism", piece:"ClassItem", synergy:["Any"], grants:[], effects:[], note:"Prismatic-only exotic class item — pick 2 perks below (one per column)"},
  ],
  Warlock: [
    // Solar
    {name:"Sunbracers", piece:"Arms", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"grenadeEnergy",value:15,note:"melee kills grant infinite Solar grenades briefly"}]},
    {name:"Starfire Protocol", piece:"Chest", synergy:["Solar"], grants:[], effects:[{bucket:"grenadeEnergy",value:12,note:"empowered kills grant grenade energy; grenade kills grant rift energy"}]},
    {name:"Phoenix Protocol", piece:"Chest", synergy:["Solar"], grants:["radiant"], effects:[{bucket:"superEnergy",value:18,note:"kills/assists in Well of Radiance return Super energy"}]},
    {name:"Dawn Chorus", piece:"Head", synergy:["Solar"], grants:["scorch"], effects:[{bucket:"meleeEnergy",value:10,cond:"scorch"},{bucket:"damage",value:8,cond:"scorch"}]},
    {name:"Wings of Sacred Dawn", piece:"Chest", synergy:["Solar"], grants:[], effects:[{bucket:"dr",value:8,note:"mid-air suspension while aiming Solar weapons"}]},
    {name:"Speaker's Sight", piece:"Head", synergy:["Solar"], grants:["restoration"], effects:[{bucket:"healing",value:12,note:"Healing Grenade becomes a Restorative Turret"}]},
    {name:"Promethium Spur", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:10,note:"Solar kills in Rift spawn healing/empowering pools"}]},
    // Arc
    {name:"Crown of Tempests", piece:"Head", synergy:["Arc"], grants:["jolt"], effects:[{bucket:"superEnergy",value:12,cond:"jolt"}]},
    {name:"Getaway Artist", piece:"Arms", synergy:["Arc"], grants:["amplified"], effects:[{bucket:"grenadeEnergy",value:10,note:"consume grenade for a supercharged Arc Soul"}]},
    {name:"Stormdancer's Brace", piece:"Chest", synergy:["Arc"], grants:[], effects:[{bucket:"damage",value:12,note:"Stormtrance damage increases weapon dmg output"}]},
    {name:"Geomag Stabilizers", piece:"Legs", synergy:["Arc"], grants:[], effects:[{bucket:"damage",value:15,note:"sprinting tops off Chaos Reach, traces extend it"}]},
    // Void
    {name:"Nezarec's Sin", piece:"Head", synergy:["Void"], grants:[], effects:[{bucket:"superEnergy",value:10,note:"Void kills buff all ability recharge"}]},
    {name:"Contraverse Hold", piece:"Arms", synergy:["Void"], grants:["weaken"], effects:[{bucket:"grenadeEnergy",value:12,cond:"weaken"},{bucket:"dr",value:10,note:"dr while charging Void grenade"}]},
    {name:"Skull of Dire Ahamkara", piece:"Head", synergy:["Void"], grants:[], effects:[{bucket:"dr",value:10,note:"dr during Nova Bomb"},{bucket:"superEnergy",value:8,note:"Super energy on kills"}]},
    {name:"Nothing Manacles", piece:"Arms", synergy:["Void"], grants:[], effects:[{bucket:"grenadeEnergy",value:10,note:"extra Scatter Grenade charge + tracking"}]},
    {name:"Briarbinds", piece:"Arms", synergy:["Void"], grants:[], effects:[{bucket:"healing",value:8,note:"redeploy Void Soul with more duration/damage"},{bucket:"damage",value:6}]},
    {name:"Secant Filaments", piece:"Legs", synergy:["Void"], grants:["devour"], effects:[{bucket:"healing",value:10,cond:"devour",note:"Empowering Rift grants Devour"}]},
    {name:"Felwinter's Helm", piece:"Head", synergy:["Any"], grants:["weaken"], effects:[{bucket:"damage",value:10,cond:"weaken",note:"powered melee kills weaken nearby targets"}]},
    // Strand
    {name:"Swarmers", piece:"Legs", synergy:["Strand"], grants:["tangle","suspend"], effects:[{bucket:"grenadeEnergy",value:12,cond:"tangle"}]},
    {name:"Mataiodoxia", piece:"Chest", synergy:["Strand"], grants:["suspend"], effects:[{bucket:"meleeEnergy",value:10,cond:"suspend",note:"marked targets emit suspending detonation"}]},
    // Stasis
    {name:"Osmiomancy Gloves", piece:"Arms", synergy:["Stasis"], grants:["frozen"], effects:[{bucket:"grenadeEnergy",value:15,cond:"frozen"}]},
    {name:"Ballidorse Wrathweavers", piece:"Arms", synergy:["Stasis"], grants:["frozen","overshield"], effects:[{bucket:"damage",value:10,note:"buffs Stasis super"},{bucket:"dr",value:8,cond:"overshield",note:"overshield to allies on shatter"}]},
    {name:"Rime-Coat Raiment", piece:"Chest", synergy:["Stasis"], grants:["frozen"], effects:[{bucket:"grenadeDamage",value:12,note:"enhances Stasis turret performance"}]},
    // Neutral
    {name:"Aeon Soul", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"team-based ammo/ability energy utility"}]},
    {name:"Apotheosis Veil", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:15,note:"Super cast regens all melee/grenade/rift energy"}]},
    {name:"Astrocyte Verse", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:10},{bucket:"dr",value:6,note:"improved Blink + teleport window"}]},
    {name:"Boots of the Assembler", piece:"Legs", synergy:["Any"], grants:["radiant"], effects:[{bucket:"healing",value:10,note:"Rift seekers heal or buff allies"}]},
    {name:"Chromatic Fire", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"damage",value:10,note:"precision Kinetic kills create subclass-element explosions"}]},
    {name:"Claws of Ahamkara", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeEnergy",value:12,note:"extra melee charge + energy on hit"}]},
    {name:"Cenotaph Mask", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"auto-reloads Trace Rifles, marks priority targets"}]},
    {name:"Eye of Another World", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"highlights priority targets, ability recharge"}]},
    {name:"Fallen Sunstar", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:8,note:"improves Ionic Trace generation, energy to allies"}]},
    {name:"Karnstein Armlets", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:12,note:"melee kill heal"}]},
    {name:"Lunafaction Boots", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"reload speed for allies in Rift/Well"}]},
    {name:"Mantle of Battle Harmony", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"superEnergy",value:8,cond:"matching-element",note:"kills matching Super element grant Super energy"}]},
    {name:"Necrotic Grip", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeDamage",value:14,note:"poison spread on melee"}]},
    {name:"Ophidian Aspect", piece:"Arms", synergy:["Any"], grants:[], effects:[{bucket:"meleeEnergy",value:6,note:"weapon ready/reload/melee range boost"}]},
    {name:"Rain of Fire", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"dodge reloads weapons + airborne accuracy"}]},
    {name:"Sanguine Alchemy", piece:"Chest", synergy:["Any"], grants:[], effects:[{bucket:"healing",value:8,note:"extends Rift duration"},{bucket:"damage",value:6,note:"dmg bonus inside Rift"}]},
    {name:"The Stag", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"dr",value:8,note:"dr in rifts"},{bucket:"healing",value:6,note:"rift energy on crit-health"}]},
    {name:"Transversive Steps", piece:"Legs", synergy:["Any"], grants:[], effects:[{bucket:"classEnergy",value:6,note:"sprint reloads equipped weapon"}]},
    {name:"Verity's Brow", piece:"Head", synergy:["Any"], grants:[], effects:[{bucket:"grenadeDamage",value:12},{bucket:"meleeDamage",value:12}]},
    {name:"Vesper of Radius", piece:"Chest", synergy:["Void"], grants:["weaken"], effects:[{bucket:"grenadeEnergy",value:10,cond:"weaken",note:"Rift releases periodic Arc shockwave"}]},
    {name:"Winter's Guile", piece:"Arms", synergy:["Stasis"], grants:["frozen"], effects:[{bucket:"meleeDamage",value:16,cond:"frozen"}]},
    // Prismatic-only exotic class item
    {name:"Solipsism", piece:"ClassItem", synergy:["Any"], grants:[], effects:[], note:"Prismatic-only exotic class item — pick 2 perks below (one per column)"},
  ],
};

// ---- EXOTIC CLASS ITEM PERK POOLS (Prismatic-only) ----
// Each class has exactly one named exotic class item (Essentialism/Stoicism/
// Solipsism). It carries no fixed effect of its own — its power comes from
// picking one "Spirit of X" perk from Column 1 and one from Column 2, each
// borrowing the intrinsic effect of the named exotic armor piece X.
const EXOTIC_CLASS_ITEM_PERKS = {
  Hunter: {
    name: "Essentialism",
    column1: [
      {name:"Spirit of the Assassin", grants:["invisible"], effects:[{bucket:"healing",value:10,cond:"invisible"}]},
      {name:"Spirit of the Inmost Light", grants:[], effects:[{bucket:"meleeEnergy",value:8},{bucket:"grenadeEnergy",value:8},{bucket:"classEnergy",value:8}]},
      {name:"Spirit of the Ophidian", grants:[], effects:[{bucket:"meleeEnergy",value:5,note:"weapon handling/reload/ready speed"}]},
      {name:"Spirit of the Dragon", grants:[], effects:[{bucket:"classEnergy",value:8,note:"reload speed on dodge"}]},
      {name:"Spirit of the Liar", grants:[], effects:[{bucket:"meleeDamage",value:10},{bucket:"healing",value:6}]},
      {name:"Spirit of the Wormhusk", grants:[], effects:[{bucket:"healing",value:8,note:"heal on dodge"}]},
      {name:"Spirit of the Renewal", grants:["frozen"], effects:[{bucket:"grenadeDamage",value:10,cond:"frozen"}]},
      {name:"Spirit of the Galanor", grants:["scorch"], effects:[{bucket:"superEnergy",value:12,note:"Blade Barrage kill energy return"}]},
    ],
    column2: [
      {name:"Spirit of the Star-Eater", grants:[], effects:[{bucket:"damage",value:14,note:"consumes orbs to buff super"}]},
      {name:"Spirit of the Synthoceps", grants:[], effects:[{bucket:"meleeDamage",value:10,note:"while surrounded"}]},
      {name:"Spirit of Verity", grants:[], effects:[{bucket:"grenadeDamage",value:8},{bucket:"meleeDamage",value:8}]},
      {name:"Spirit of the Cyrtarachne", grants:["woven-mail"], effects:[{bucket:"dr",value:8,cond:"woven-mail"}]},
      {name:"Spirit of Caliban", grants:["scorch","ignite"], effects:[{bucket:"meleeDamage",value:8,note:"proximity knives cause ignitions"}]},
      {name:"Spirit of the Gyrfalcon", grants:["invisible","volatile"], effects:[{bucket:"damage",value:8,cond:"volatile"}]},
      {name:"Spirit of the Coyote", grants:[], effects:[{bucket:"classEnergy",value:8,note:"extra dodge charge"}]},
      {name:"Spirit of the Punchy", grants:[], effects:[{bucket:"meleeDamage",value:10,note:"punch-focused melee buff"}]},
    ],
  },
  Titan: {
    name: "Stoicism",
    column1: [
      {name:"Spirit of the Inmost Light", grants:[], effects:[{bucket:"meleeEnergy",value:8},{bucket:"grenadeEnergy",value:8},{bucket:"classEnergy",value:8}]},
      {name:"Spirit of the Horn", grants:["scorch"], effects:[{bucket:"classEnergy",value:8,note:"weapon kills recharge Barricade"}]},
      {name:"Spirit of the Alpha Lupi", grants:[], effects:[{bucket:"healing",value:8,note:"class ability cast heals nearby allies"}]},
      {name:"Spirit of the Scars", grants:[], effects:[{bucket:"healing",value:10,cond:"matching-element"}]},
      {name:"Spirit of the Armamentarium", grants:[], effects:[{bucket:"grenadeEnergy",value:6,note:"extra grenade charge"}]},
      {name:"Spirit of the Point-Contact", grants:["jolt"], effects:[{bucket:"damage",value:10,cond:"jolt"}]},
      {name:"Spirit of the Hoarfrost", grants:["overshield"], effects:[{bucket:"dr",value:14,cond:"frozen"}]},
      {name:"Spirit of the Undertow", grants:[], effects:[{bucket:"dr",value:8,note:"utility survivability buff"}]},
    ],
    column2: [
      {name:"Spirit of the Synthoceps", grants:[], effects:[{bucket:"meleeDamage",value:10,note:"while surrounded"}]},
      {name:"Spirit of the Abeyant", grants:["suspend"], effects:[{bucket:"meleeEnergy",value:10,cond:"suspend"}]},
      {name:"Spirit of the Severance", grants:[], effects:[{bucket:"damage",value:10,note:"death-triggered explosion"}]},
      {name:"Spirit of the Star-Eater", grants:[], effects:[{bucket:"damage",value:14,note:"consumes orbs to buff super"}]},
      {name:"Spirit of the Precious Scars", grants:["restoration"], effects:[{bucket:"healing",value:10,cond:"restoration"}]},
      {name:"Spirit of the Contact", grants:["jolt"], effects:[{bucket:"meleeEnergy",value:8,cond:"jolt"}]},
      {name:"Spirit of the Thruster", grants:[], effects:[{bucket:"classEnergy",value:8,note:"mobility/traversal buff"}]},
      {name:"Spirit of the Citan", grants:[], effects:[{bucket:"dr",value:8,note:"allies can shoot through Barricade"}]},
    ],
  },
  Warlock: {
    name: "Solipsism",
    column1: [
      {name:"Spirit of Verity", grants:[], effects:[{bucket:"grenadeDamage",value:8},{bucket:"meleeDamage",value:8}]},
      {name:"Spirit of Vesper", grants:["weaken"], effects:[{bucket:"grenadeEnergy",value:8,cond:"weaken"}]},
      {name:"Spirit of Harmony", grants:[], effects:[{bucket:"grenadeEnergy",value:6},{bucket:"classEnergy",value:6}]},
      {name:"Spirit of Starfire", grants:[], effects:[{bucket:"grenadeEnergy",value:10,note:"grenade energy refund after Empowering Rift"}]},
      {name:"Spirit of the Swarm", grants:["tangle","suspend"], effects:[{bucket:"grenadeEnergy",value:10,cond:"tangle"}]},
      {name:"Spirit of the Claw", grants:[], effects:[{bucket:"meleeEnergy",value:10,note:"extra melee charge + energy on hit"}]},
      {name:"Spirit of the Inmost Light", grants:[], effects:[{bucket:"meleeEnergy",value:8},{bucket:"grenadeEnergy",value:8},{bucket:"classEnergy",value:8}]},
      {name:"Spirit of the Assassin", grants:["invisible"], effects:[{bucket:"healing",value:10,cond:"invisible"}]},
    ],
    column2: [
      {name:"Spirit of the Stag", grants:[], effects:[{bucket:"healing",value:10,note:"rift healing buff"}]},
      {name:"Spirit of the Filaments", grants:["woven-mail"], effects:[{bucket:"healing",value:8,cond:"woven-mail"}]},
      {name:"Spirit of the Necrotic", grants:[], effects:[{bucket:"meleeDamage",value:10,note:"poison spread on melee"}]},
      {name:"Spirit of Osmiomancy", grants:["frozen"], effects:[{bucket:"grenadeEnergy",value:12,cond:"frozen"}]},
      {name:"Spirit of Apotheosis", grants:[], effects:[{bucket:"healing",value:12,note:"rift grants overshield + healing"}]},
      {name:"Spirit of the Star-Eater", grants:[], effects:[{bucket:"damage",value:14,note:"consumes orbs to buff super"}]},
      {name:"Spirit of the Synthoceps", grants:[], effects:[{bucket:"meleeDamage",value:10,note:"while surrounded"}]},
      {name:"Spirit of Verity", grants:[], effects:[{bucket:"grenadeDamage",value:8},{bucket:"meleeDamage",value:8}]},
    ],
  },
};



// slot = which weapon-slot dropdown it lives under: Kinetic = Top slot,
// Energy = Middle slot, Power = Bottom/Heavy slot. Only one exotic weapon
// total can be equipped at once, same as in-game. Roster and slot placement
// follow the user's corrected list exactly; elements assigned from real D2
// knowledge, constrained to each slot's allowed damage types (Top: Kinetic/
// Stasis/Strand, Middle: Arc/Solar/Void, Bottom: any).
// ---- WEAPON INTRINSIC PERKS ----
// The actual named exotic intrinsic trait for each weapon (not a synergy
// summary). Descriptions are paraphrased in our own words rather than
// quoted verbatim from the game. Weapons without an entry here fall back to
// the effect-based summary in the UI.
const WEAPON_INTRINSICS = {
  "Ace of Spades": {perk:"Memento Mori", desc:"Reloading after a kill chambers a single high-damage round with bonus precision damage and a brief accuracy boost."},
  "Arbalest": {perk:"Compressed Aerospacer", desc:"Charged shots pierce shields and deal bonus precision damage to the target hit right after."},
  "Bad Juju": {perk:"Rewind", desc:"Kills increase rate of fire and automatically reload the magazine, and grant Super energy."},
  "Cerberus+1": {perk:"Multitool", desc:"Aiming at an enemy causes some shots to track toward them."},
  "The Chaperone": {perk:"One Shot, One Kill", desc:"Massively increased precision damage and improved handling, at the cost of no aim-assist while hip-fired."},
  "Conditional Finality": {perk:"One and Done", desc:"The left barrel freezes with Stasis shards, the right ignites a scorching pool — alternate fire switches barrels."},
  "Crimson": {perk:"Cascade", desc:"Precision hits shorten the burst delay and heal you; hip-fire has improved accuracy."},
  "Dead Man's Tale": {perk:"Or Not to Be", desc:"Hip-fire mode grants increased range and accuracy; precision hits load extra rounds into the next burst."},
  "Final Warning": {perk:"Compass Rose", desc:"Fired projectiles track toward wherever you're aiming, curving to hit the target."},
  "Forerunner": {perk:"Ready Ammo", desc:"Alternate fire launches all remaining ammo as one tracking burst that deals heavy damage."},
  "The Huckleberry": {perk:"Big Iron", desc:"Landing three hits in semi-auto swaps the weapon to full-auto for a short time."},
  "Izanagi's Burden": {perk:"Honed Edge", desc:"Reloading after firing loads a single powerful precision round with bonus damage."},
  "The Jade Rabbit": {perk:"Fate of All Fools", desc:"Chaining precision shots or precision final blows refills the magazine, improves stability, and greatly boosts Firefly and body-shot damage — a body shot removes one stack of the bonus."},
  "Lumina": {perk:"Noble Rounds", desc:"Precision kills build stacks; activating Noble Rounds heals and empowers nearby allies for a short time."},
  "Malfeasance": {perk:"Explosive Personality", desc:"Hits apply a stacking detonation charge; the fifth stack detonates for heavy damage."},
  "MIDA Multi-Tool": {perk:"Memory of Felwinter", desc:"Improves mobility and weapon handling, and increases class ability regeneration speed."},
  "Monte Carlo": {perk:"Monte Carlo Method", desc:"Melee hits instantly reload the weapon and grant a brief damage buff."},
  "Necrochasm": {perk:"Cursed Thrall", desc:"Kills release a chain of cursed explosions that can spread to nearby enemies."},
  "No Time to Explain": {perk:"Or Was It", desc:"Alternate fire opens a temporary portal that fires alongside you."},
  "Osteo Striga": {perk:"Contagion", desc:"Hits apply a stacking poison that ramps in damage over time."},
  "Outbreak Perfected": {perk:"Parasitism", desc:"Kills release a swarm of nanites that chains to nearby enemies and deals damage over time."},
  "Quicksilver Storm": {perk:"Subtunnel Charge", desc:"Landing kills charges a homing micro-missile volley that fires automatically."},
  "Rat King": {perk:"Ambush Predator", desc:"Kills grant brief invisibility while stationary; squading up with other Rat King wielders buffs the whole group."},
  "Revision Zero": {perk:"Adaptive Munitions", desc:"Lets you swap between two stored perk/frame configurations on demand."},
  "Still Hunt": {perk:"Solar Wind", desc:"Precision kills charge a single high-damage Golden Gun-style bonus round."},
  "Sturm": {perk:"Ally-Up", desc:"Dealing damage with its paired sidearm (Drang) charges a bonus-damage round on swap back to Sturm."},
  "SUROS Regime": {perk:"Focused Fire", desc:"Stability increases the longer you fire continuously."},
  "Sweet Business": {perk:"Cyclic Fire", desc:"Rate of fire ramps up the longer the trigger is held."},
  "Thorn": {perk:"Mark of the Devourer", desc:"Hits apply a damage-over-time mark that also reduces the target's healing."},
  "Traveler's Chosen": {perk:"Ophiuchus Solution", desc:"Precision hits reduce Super cooldown, and kills spawn Orbs of Power for the team."},
  "Vigilance Wing": {perk:"Bad Omens", desc:"When a squadmate is critically wounded or the team wipes, surviving members gain a strong combat buff."},
  "Wish-Ender": {perk:"Broadhead", desc:"Reveals enemies through walls while aiming, and fires three simultaneous damage instances per hit."},
  "Cull's Shadow": {perk:"Soulburn", desc:"Rapid or final hits with the weapon's frontal blades heal you and build Soulfire Charges, which let fired rounds inflict a stacking corruption debuff."},
  "Witherhoard": {perk:"Villainy", desc:"Rounds create a lingering blight pool that deals damage over time, even while you swap weapons."},

  "Borealis": {perk:"Ionic Return", desc:"Breaking a shield matching this weapon's current element refills the magazine from reserves and grants bonus damage for the rest of the mag. A separate perk, The Fundamentals, lets you swap its damage type between Arc, Solar, and Void."},
  "Buried Bloodline": {perk:"Never Missed a Day", desc:"Weakening a target and then killing it activates Devour, healing you on subsequent kills."},
  "Cloudstrike": {perk:"Tempest Strike", desc:"Precision kills call down a lightning strike on the target's location."},
  "Coldheart": {perk:"Convection", desc:"Continuous fire ramps the beam's damage the longer it's held on target."},
  "Collective Obligation": {perk:"Universal Wavefunction Collapse", desc:"Marks a target as vulnerable to whichever debuffs are present on your subclass, then detonates on final blow."},
  "Delicate Tomb": {perk:"Fated for All", desc:"Fires a burst of Stasis shards that track toward and freeze nearby enemies."},
  "Devil's Ruin": {perk:"Prometheus Gaze", desc:"Alternate fire charges a beam mode that deals sustained precision damage."},
  "Divinity": {perk:"Fatebringer's Vision", desc:"Creates a debuff aura around the target that guarantees critical hits from any weapon and weakens the target."},
  "Duality": {perk:"Impact Extraction", desc:"Alternate fire switches between shotgun and grenade-launcher modes."},
  "Eriana's Vow": {perk:"Transcendent Blade", desc:"A charged melee attack empowers the next shot to be a guaranteed one-shot kill against most combatants."},
  "Graviton Lance": {perk:"Herd Instinct", desc:"Precision kills against weakened targets chain a small Void explosion to nearby enemies."},
  "Hard Light": {perk:"Volatile Light", desc:"Rounds have no damage falloff, overpenetrate targets, and ricochet off hard surfaces \u2014 each bounce increases the bullet's damage. A separate perk, The Fundamentals, lets you hold reload to cycle its damage type between Arc, Solar, and Void."},
  "Hawkmoon": {perk:"Paracausal Shot", desc:"A hidden roulette occasionally lines up a guaranteed critical hit; landing it starts a damage-boosting streak."},
  "Ice Breaker": {perk:"Rime", desc:"Slowly regenerates its own ammo reserve over time even when not equipped."},
  "Jötunn": {perk:"Kinetic Weaponry", desc:"Fires a slow-moving tracking orb that detonates in a large Solar explosion."},
  "Le Monarque": {perk:"Gutted", desc:"Hits apply a poison cloud that spreads to nearby enemies and deals damage over time."},
  "Lord of Wolves": {perk:"Roar of the Bear", desc:"Activating its breather mode switches to a faster, more accurate full-auto burst for a short time."},
  "Merciless": {perk:"Corrective Measure", desc:"Rapid precision hits trigger an automatic second burst without needing to recharge."},
  "Prometheus Lens": {perk:"Precision Fire", desc:"Sustained beam fire ramps up its damage output the longer it stays on target."},
  "Red Death Reformed": {perk:"Reanimated", desc:"Landing hits heals you, and reloading after a kill grants a temporary healing regeneration buff."},
  "Riskrunner": {perk:"Superconductor", desc:"Taking Arc damage grants temporary damage immunity and causes your shots to jolt enemies."},
  "Ruinous Effigy": {perk:"Impossible Machines", desc:"Charged melee marks an enemy; firing at the mark detonates it and heals you and nearby allies."},
  "Sunshot": {perk:"Explosive Rounds", desc:"Kills cause the target to explode, chaining Solar damage to other nearby enemies."},
  "Symmetry": {perk:"Metamorphosis", desc:"Alternate fire swaps between a pulse-rifle burst and a fusion-rifle burst firing mode."},
  "Tarrabah": {perk:"Feeding Frenzy (Unique)", desc:"Dealing damage builds toward a 'Feeding Frenzy' full-auto burst mode with a large damage bonus."},
  "Telesto": {perk:"Sticky Rounds", desc:"Rounds stick to surfaces and enemies before detonating, and can trigger other Void debuff interactions."},
  "The Fourth Horseman": {perk:"Micro-Missile Ordnance", desc:"Fires all barrels at once in a wide spread for a devastating close-range burst."},
  "The Last Word": {perk:"Fan Fire", desc:"Improved accuracy and damage while hip-fired in a rapid clicking rhythm."},
  "Ticuu's Divination": {perk:"Incendiary Rounds", desc:"Fully-drawn shots fire a cluster of tracking, explosive flaming arrows."},
  "Tommy's Matchbook": {perk:"For the Family", desc:"Kills heal you and nearby allies, and reloading grants a brief healing pulse."},
  "Trespasser": {perk:"Fealty", desc:"Swapping to this weapon fully reloads it from reserves."},
  "Trinity Ghoul": {perk:"Lightning Rod", desc:"Fully-drawn shots split into three arrows; kills release a chain of lightning bolts to nearby enemies."},
  "Vex Mythoclast": {perk:"Transdimensional Descoping", desc:"Alternates between a precision fusion-rifle mode and a full-auto rifle mode."},
  "Wavesplitter": {perk:"Corrosive Current", desc:"Holding the trigger builds an overload charge that unleashes a high-damage burst on release."},
  "Turncoat": {perk:"Latent Power", desc:"Precision hits and kills build a power meter; activating it empowers every shot to weaken targets, at the cost of self-damage over time while active."},

  "1000 Voices": {perk:"Prophetic Cadence", desc:"Fires a sustained beam that also launches slow-tracking explosive orbs."},
  "Anarchy": {perk:"Arc Conductor", desc:"Attached shock traps deal initial damage, then a stronger follow-up burst shortly after."},
  "Black Talon": {perk:"Rip and Tear", desc:"Heavy attacks launch a Void projectile that slashes through enemies in a line."},
  "The Colony": {perk:"Broodmother", desc:"Fired grenades burrow into the ground and spawn tracking mechanical spiders that detonate on contact."},
  "Darci": {perk:"Personal Assistant", desc:"Aiming at an enemy displays live damage-dealt data and grants a brief precision damage buff."},
  "Deathbringer": {perk:"Anti-Matter", desc:"Fires a tracking projectile that deals heavy Void damage and can chain to additional targets."},
  "Dragon's Breath": {perk:"Match Bearer", desc:"Fires a tracking napalm rocket that leaves a burning trail and detonates on impact."},
  "Eyes of Tomorrow": {perk:"Precognitive Missiles", desc:"Locks onto up to six targets and fires a full volley of tracking rockets."},
  "Gjallarhorn": {perk:"Wolfpack Rounds", desc:"On detonation, releases a burst of tracking micro-missiles that deal additional damage."},
  "Grand Overture": {perk:"All Aboard", desc:"Sustained fire spins up increasing rate of fire and periodically summons Arc-charged train cars that fire alongside you."},
  "Heartshadow": {perk:"Vanishing Blade", desc:"Sprinting or sliding after a kill grants brief invisibility."},
  "Hierarchy of Needs": {perk:"Erasure", desc:"Fully-drawn precision shots detonate on impact for bonus explosive damage."},
  "Legend of Acrius": {perk:"Impact Cannon", desc:"Fires a wide, high-damage burst effective at both close and long range."},
  "Leviathan's Breath": {perk:"Big Chief", desc:"A powerful draw-based bow shot that knocks back and staggers groups of enemies in a line."},
  "Microcosm": {perk:"Melded Singularity", desc:"Fires a miniature collapsing singularity that deals continuous damage while passing through enemies."},
  "Parasite": {perk:"Antihost", desc:"Grenades deal more damage the farther they travel before detonating, tracking distance since your last kill."},
  "Salvation's Grip": {perk:"Shattersnap", desc:"Fires a growing wave of Stasis crystals that freezes everything in its path."},
  "Sleeper Simulant": {perk:"Transdimensional Transposer", desc:"Charges a beam that ricochets off surfaces, dealing bonus damage on each bounce."},
  "The Lament": {perk:"Cadence", desc:"Revving the weapon before combat and landing hits builds toward automatic guard-breaking heavy strikes."},
  "The Prospector": {perk:"Proximity Detonation", desc:"Fires bouncing proximity mines that detonate when enemies get close."},
  "The Wardcliff Coil": {perk:"Excess Ordnance", desc:"Fires a burst of six unguided rockets simultaneously, like a rocket-powered shotgun."},
  "Thunderlord": {perk:"Stormbringer", desc:"Sustained fire builds stacks that periodically call down lightning strikes on nearby enemies."},
  "Tractor Cannon": {perk:"Repulsor Force", desc:"Fires a burst of force that knocks back and weakens enemies caught in it."},
  "Truth": {perk:"Guidance Ring", desc:"Fires a slow-tracking heavy-damage rocket that follows the targeted enemy."},
  "Two-Tailed Fox": {perk:"Pyre", desc:"Fires a paired Solar and Void rocket simultaneously for a combined detonation."},
  "Whisper of the Worm": {perk:"White Nail", desc:"Consecutive precision hits refund ammunition, allowing an extended chain of high-damage shots."},
  "Whirling Ovation": {perk:"Continuous Harmonic Tremors", desc:"Blocking builds stacks that empower the next heavy attack with bonus damage."},
  "Winterbite": {perk:"Broadhead Tips", desc:"Charged heavy attacks fire a piercing Stasis projectile that freezes and shatters enemies in a line."},
  "Xenophage": {perk:"Reforged", desc:"A slow-firing, high-damage weapon built for sustained single-target boss damage."},
  "Fafnir": {perk:"Quantum Nova", desc:"An alternate action consumes reserve ammo to overcharge the weapon, applying a strong Weaken debuff for a duration that scales with ammo spent."},
};

const EXOTIC_WEAPONS = [
  // --- Top slot (Kinetic / Stasis / Strand) ---
  {name:"Ace of Spades", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"Firefly + Memento Mori reload chain"}]},
  {name:"Ager's Scepter", slot:"Kinetic", element:"Stasis", grants:["frozen"], effects:[{bucket:"damage",value:12,cond:"frozen"}]},
  {name:"Alethonym", slot:"Kinetic", element:"Strand", grants:["sever"], effects:[{bucket:"damage",value:10,cond:"sever"}]},
  {name:"Arbalest", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"charged shot breaks shields, precision follow-up"}]},
  {name:"Bad Juju", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"superEnergy",value:10,note:"kills grant super energy"}]},
  {name:"Bastion", slot:"Kinetic", element:"Kinetic", grants:["overshield"], effects:[{bucket:"dr",value:8,cond:"overshield"}]},
  {name:"Cerberus+1", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:8,note:"tracking shots vs marked target"}]},
  {name:"The Chaperone", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"precision-focused shotgun-sidearm hybrid"}]},
  {name:"Conditional Finality", slot:"Kinetic", element:"Stasis", grants:["frozen"], effects:[{bucket:"damage",value:12,cond:"frozen"}]},
  {name:"Crimson", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"healing",value:8},{bucket:"damage",value:8}]},
  {name:"Cryosthesia 77K", slot:"Kinetic", element:"Stasis", grants:["frozen"], effects:[{bucket:"damage",value:8,cond:"frozen"}]},
  {name:"Dead Man's Tale", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10,note:"scout/pulse hybrid precision"}]},
  {name:"Final Warning", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10,note:"tracking projectiles"}]},
  {name:"Forerunner", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:9,note:"rapid-fire sidearm"}]},
  {name:"The Huckleberry", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:9,note:"rampage stacks feed full-auto"}]},
  {name:"Izanagi's Burden", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:20,note:"charge-shot sniper, honed edge follow-up"}]},
  {name:"The Jade Rabbit", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"healing",value:8},{bucket:"damage",value:8,note:"precision kill heal + accuracy buff"}]},
  {name:"Khvostov 7G-0X", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:8,note:"multi-perk configurable AR"}]},
  {name:"Lumina", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"healing",value:12,note:"precision kills grant Noble Rounds heal"}]},
  {name:"Malfeasance", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:14,note:"stacking detonation"}]},
  {name:"MIDA Multi-Tool", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"classEnergy",value:6},{bucket:"damage",value:6}]},
  {name:"Monte Carlo", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"meleeEnergy",value:10,note:"melee energy on hit"}]},
  {name:"Navigator", slot:"Kinetic", element:"Strand", grants:["suspend"], effects:[{bucket:"damage",value:12,cond:"suspend"}]},
  {name:"Necrochasm", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:14,note:"chain detonation on kill"}]},
  {name:"No Time to Explain", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10,note:"time-portal projectiles"}]},
  {name:"Osteo Striga", slot:"Kinetic", element:"Kinetic", grants:["poison-proxy"], effects:[{bucket:"damage",value:14,note:"poison DoT stacking"}]},
  {name:"Outbreak Perfected", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"nanite swarm chain"}]},
  {name:"Quicksilver Storm", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"auto-loading missile bursts"}]},
  {name:"Rat King", slot:"Kinetic", element:"Kinetic", grants:["invisible"], effects:[{bucket:"damage",value:8},{bucket:"healing",value:6}]},
  {name:"Revision Zero", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10,note:"switchable frame/perks"}]},
  {name:"Service of Luzaku", slot:"Kinetic", element:"Strand", grants:["tangle"], effects:[{bucket:"damage",value:10,cond:"tangle"}]},
  {name:"Still Hunt", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:16,note:"precision sniper w/ Golden Gun echo shot"}]},
  {name:"Sturm", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:14,note:"bonus dmg after Drang swap"}]},
  {name:"SUROS Regime", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:8,note:"stability ramp on sustained fire"}]},
  {name:"Sweet Business", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:8,note:"spin-up minigun-style AR"}]},
  {name:"Thorn", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:13,note:"DoT + healing denial"}]},
  {name:"Traveler's Chosen", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"superEnergy",value:8,note:"orb-focused hand cannon"}]},
  {name:"Verglas Curve", slot:"Kinetic", element:"Stasis", grants:["frozen"], effects:[{bucket:"damage",value:8,cond:"frozen"}]},
  {name:"Vigilance Wing", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"healing",value:8,note:"squad wipe recovery buff"}]},
  {name:"Wicked Implement", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10}]},
  {name:"Wish-Ender", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:14,note:"reveals enemies through walls"}]},
  {name:"Cull's Shadow", slot:"Kinetic", element:"Kinetic", grants:["poison-proxy"], effects:[{bucket:"healing",value:6,note:"Soulburn: frontal blade hits heal + build Soulfire Charges"},{bucket:"damage",value:12,note:"corruption-afflicted targets take more dmg"}]},
  {name:"Witherhoard", slot:"Kinetic", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"lingering blight DoT pool"}]},

  // --- Middle slot (Arc / Solar / Void) ---
  {name:"Borealis", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:12,cond:"jolt",note:"element-adaptive sniper — The Fundamentals lets you cycle Arc/Solar/Void; set to whichever matches your subclass"}]},
  {name:"Buried Bloodline", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"healing",value:6},{bucket:"damage",value:10,cond:"weaken"}]},
  {name:"Centrifuse", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:10,cond:"jolt"}]},
  {name:"Choir of One", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:10,cond:"scorch"},{bucket:"dr",value:6,note:"projected shield block"}]},
  {name:"Cloudstrike", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:14,note:"lightning strike on precision kill"}]},
  {name:"Coldheart", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:9,note:"ramping beam damage"}]},
  {name:"Collective Obligation", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:10,cond:"weaken"}]},
  {name:"Dead Messenger", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:10,note:"tracking mine submunitions — The Fundamentals lets you cycle Arc/Solar/Void; set to whichever matches your subclass"}]},
  {name:"Delicate Tomb", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:10}]},
  {name:"Devil's Ruin", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:10,note:"charged beam mode"}]},
  {name:"Divinity", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:10,cond:"weaken",note:"crit-spot debuff aura for team"}]},
  {name:"Duality", slot:"Energy", element:"Void", grants:["weaken","invisible"], effects:[{bucket:"damage",value:12,note:"shotgun/GL hybrid"}]},
  {name:"Edge of Action", slot:"Energy", element:"Arc", grants:[], effects:[{bucket:"meleeDamage",value:10}]},
  {name:"Edge of Concurrence", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"meleeDamage",value:10,cond:"scorch"}]},
  {name:"Edge of Intent", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"meleeDamage",value:10,cond:"weaken"}]},
  {name:"Ergo Sum", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:12,note:"memory-weapon perk window"}]},
  {name:"Eriana's Vow", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:14,note:"charged melee empowers next shot"}]},
  {name:"Fighting Lion", slot:"Energy", element:"Void", grants:["volatile"], effects:[{bucket:"damage",value:10,cond:"volatile",note:"direct hits deal bonus dmg to shields, cause a volatile detonation"}]},
  {name:"Graviton Lance", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:10,cond:"weaken"}]},
  {name:"Hard Light", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:8,note:"ricochet rounds, damage ramps per bounce — The Fundamentals lets you cycle Arc/Solar/Void; set to whichever matches your subclass"}]},
  {name:"Hawkmoon", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:14,note:"paracausal roulette crit chain"}]},
  {name:"Ice Breaker", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:12,note:"regenerating ammo reserve"}]},
  {name:"Jötunn", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:14,note:"tracking fusion orb"}]},
  {name:"Le Monarque", slot:"Energy", element:"Void", grants:["poison-proxy"], effects:[{bucket:"damage",value:12,note:"poison cloud on hit"}]},
  {name:"Lord of Wolves", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:10,note:"breather mode rapid-fire"}]},
  {name:"Merciless", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:10,note:"double-fire on rapid precision"}]},
  {name:"Prometheus Lens", slot:"Energy", element:"Solar", grants:[], effects:[{bucket:"damage",value:9,note:"heat-scaling beam"}]},
  {name:"Red Death Reformed", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"healing",value:10},{bucket:"damage",value:8,cond:"scorch"}]},
  {name:"Riskrunner", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:12,cond:"jolt"},{bucket:"dr",value:8,note:"arc dmg immunity proc"}]},
  {name:"Ruinous Effigy", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"healing",value:8},{bucket:"damage",value:8,cond:"weaken"}]},
  {name:"Skyburner's Oath", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:10,cond:"scorch"}]},
  {name:"Sunshot", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:12,cond:"scorch",note:"explosive chain on kill"}]},
  {name:"Symmetry", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:10,note:"swap between pulse/fusion firing modes"}]},
  {name:"Tarrabah", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:12,note:"feeds off own damage dealt"}]},
  {name:"Telesto", slot:"Energy", element:"Void", grants:["volatile"], effects:[{bucket:"damage",value:10,cond:"volatile",note:"sticky explosive rounds"}]},
  {name:"The Fourth Horseman", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:12,note:"full-auto shotgun burst"}]},
  {name:"The Last Word", slot:"Energy", element:"Solar", grants:[], effects:[{bucket:"damage",value:12,note:"hip-fire accuracy window"}]},
  {name:"The Manticore", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:10,cond:"jolt"}]},
  {name:"Ticuu's Divination", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:12,note:"tracking flaming arrows"}]},
  {name:"Tommy's Matchbook", slot:"Energy", element:"Solar", grants:["scorch"], effects:[{bucket:"healing",value:8},{bucket:"damage",value:8}]},
  {name:"Trespasser", slot:"Energy", element:"Void", grants:[], effects:[{bucket:"damage",value:8,note:"exotic sidearm, reload-on-swap"}]},
  {name:"Trinity Ghoul", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:14,cond:"jolt",note:"chain-lightning arrows"}]},
  {name:"Vexcalibur", slot:"Energy", element:"Arc", grants:["jolt","amplified"], effects:[{bucket:"meleeDamage",value:12,cond:"amplified"},{bucket:"classEnergy",value:8}]},
  {name:"Vex Mythoclast", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:12,cond:"jolt",note:"fusion/AR hybrid firing modes"}]},
  {name:"Wavesplitter", slot:"Energy", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:11,note:"charged beam overload"}]},
  {name:"Turncoat", slot:"Energy", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:12,cond:"weaken",note:"Latent Power builds via hits; Empowered Mode weakens every shot"}]},

  // --- Bottom slot (Heavy / Power) ---
  {name:"1000 Voices", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:24,note:"beam + tracking orbs"}]},
  {name:"Anarchy", slot:"Power", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:16,cond:"jolt",note:"lingering shock traps"}]},
  {name:"Black Talon", slot:"Power", element:"Void", grants:["weaken"], effects:[{bucket:"meleeDamage",value:14,note:"void projectile slash"}]},
  {name:"The Colony", slot:"Power", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:10,note:"burrowing grenade launcher spiders"}]},
  {name:"Darci", slot:"Power", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"damage readout + precision buff"}]},
  {name:"Deathbringer", slot:"Power", element:"Void", grants:[], effects:[{bucket:"damage",value:19,note:"tracking anti-matter shot"}]},
  {name:"Dragon's Breath", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:16,note:"tracking napalm rocket"}]},
  {name:"Eyes of Tomorrow", slot:"Power", element:"Solar", grants:[], effects:[{bucket:"damage",value:20,note:"6-target tracking rockets"}]},
  {name:"Gjallarhorn", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:25,note:"wolfpack round burst"}]},
  {name:"Grand Overture", slot:"Power", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:16,note:"spin-up + arc train cars"}]},
  {name:"Heartshadow", slot:"Power", element:"Void", grants:["invisible"], effects:[{bucket:"meleeDamage",value:16,note:"invis on sprint/slide after kill"}]},
  {name:"Hierarchy of Needs", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:14}]},
  {name:"Legend of Acrius", slot:"Power", element:"Solar", grants:[], effects:[{bucket:"damage",value:14,note:"shotgun-cannon hybrid"}]},
  {name:"Leviathan's Breath", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:15,note:"wave-clear bow"}]},
  {name:"Microcosm", slot:"Power", element:"Solar", grants:[], effects:[{bucket:"damage",value:18,note:"miniature black hole trace"}]},
  {name:"Parasite", slot:"Power", element:"Void", grants:[], effects:[{bucket:"damage",value:16,note:"distance-scaling detonation"}]},
  {name:"Salvation's Grip", slot:"Power", element:"Stasis", grants:["frozen","shatter"], effects:[{bucket:"damage",value:14,cond:"shatter"}]},
  {name:"Sleeper Simulant", slot:"Power", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:18,cond:"jolt"}]},
  {name:"The Lament", slot:"Power", element:"Kinetic", grants:[], effects:[{bucket:"meleeDamage",value:16,note:"revving damage ramp"}]},
  {name:"The Prospector", slot:"Power", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:12,note:"proximity mine submunitions"}]},
  {name:"The Queenbreaker", slot:"Power", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:16,note:"linear fusion precision"}]},
  {name:"The Wardcliff Coil", slot:"Power", element:"Solar", grants:[], effects:[{bucket:"damage",value:18,note:"rocket shotgun burst"}]},
  {name:"Thunderlord", slot:"Power", element:"Arc", grants:["jolt"], effects:[{bucket:"damage",value:16,cond:"jolt",note:"lightning strikes while firing"}]},
  {name:"Tractor Cannon", slot:"Power", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:8,cond:"weaken",note:"utility debuff launcher"}]},
  {name:"Truth", slot:"Power", element:"Void", grants:[], effects:[{bucket:"damage",value:18,note:"tracking rocket"}]},
  {name:"Two-Tailed Fox", slot:"Power", element:"Solar", grants:["scorch"], effects:[{bucket:"damage",value:20,note:"dual solar/void rocket pair"}]},
  {name:"Whisper of the Worm", slot:"Power", element:"Solar", grants:[], effects:[{bucket:"damage",value:22,note:"precision chain sniper"}]},
  {name:"Whirling Ovation", slot:"Power", element:"Void", grants:[], effects:[{bucket:"meleeDamage",value:12,note:"glaive block + counter"}]},
  {name:"Winterbite", slot:"Power", element:"Stasis", grants:["frozen","shatter"], effects:[{bucket:"damage",value:14,cond:"shatter"}]},
  {name:"Xenophage", slot:"Power", element:"Kinetic", grants:[], effects:[{bucket:"damage",value:18,note:"heavy sustained single-target"}]},
  {name:"Fafnir", slot:"Power", element:"Void", grants:["weaken"], effects:[{bucket:"damage",value:16,cond:"weaken",note:"Quantum Nova over-pressurizes for a strong Weaken debuff"}]},
];



